import {
  TouchableOpacity,
  Pressable,
  StyleSheet,
  Platform,
  TextInput,
  ImageBackground,
  FlatList,
  Animated,
  ScrollView,
  Modal,
  Dimensions,
  Button,
  StatusBar,
  Alert,
  Share,
  TouchableWithoutFeedback,
  ActivityIndicator,
  Linking,
} from 'react-native';
import { Image } from 'expo-image';
import View from './View';
import Text from './Text';

export default {
  TouchableOpacity,
  Pressable,
  StyleSheet,
  Platform,
  TextInput,
  Image,
  ImageBackground,
  FlatList,
  Animated,
  ScrollView,
  Modal,
  Dimensions,
  Button,
  StatusBar,
  Alert,
  View,
  Text,
  Share,
  TouchableWithoutFeedback,
  ActivityIndicator,
  Linking,
};
